version: '3.8'

services:
  # ====== Databases ======
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
      POSTGRES_USER: ${POSTGRES_USER_AUTH}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth_db -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis-auth:
    image: redis:7.4.0
    container_name: redis-auth
    environment:
      - REDIS_DATABASES=0
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 5s

  postgres-geodata:
    image: postgis/postgis:16-3.4
    container_name: postgres-geodata
    environment:
      POSTGRES_DB: ${POSTGRES_DB_GEODATA}
      POSTGRES_USER: ${POSTGRES_USER_GEODATA}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_GEODATA}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d geodata_db -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres-docs:
    image: postgres:15
    container_name: postgres-docs
    environment:
      POSTGRES_DB: ${POSTGRES_DB_DOCS}
      POSTGRES_USER: ${POSTGRES_USER_DOCS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DOCS}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d docs_db -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres-geoabstraction:
    image: postgis/postgis:16-3.4
    container_name: postgres-geoabstraction
    environment:
      POSTGRES_DB: ${POSTGRES_DB_GEOABSTRACTION}
      POSTGRES_USER: ${POSTGRES_USER_GEOABSTRACTION}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_GEOABSTRACTION}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d geoabstraction_db -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres-geoprint:
    image: postgres:15
    container_name: postgres-geoprint
    environment:
      POSTGRES_DB: ${POSTGRES_DB_GEOPRINT}
      POSTGRES_USER: ${POSTGRES_USER_GEOPRINT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_GEOPRINT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d print_db -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ====== Message Broker ======
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      # внешний доступ (для микросервисов вне docker-compose)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    depends_on:
      zookeeper:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ====== Elasticsearch for Search Service ======
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ====== TITILER ======
  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_S3_ENDPOINT=http://minio:9000
      - AWS_VIRTUAL_HOSTING=FALSE
      - PORT=8000
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - CPL_VSIL_CURL_NON_EXISTING_FILE_CACHE_TIME=0
    depends_on:
      - minio
    restart: always


  # ======= MINIO STORAGE ======
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - /minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # ====== ONLYOFFICE DOC SERVER ======
  onlyoffice-doc-server:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-doc-server
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost/healthcheck || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 40s

  # ====== MediaMTX Stream Server ======
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx
    environment:
      - MTX_API=yes
      - MTX_AUTHMETHOD=http
      - MTX_AUTHHTTPADDRESS=http://stream-service:9006/api/streams/auth
      - MTX_AUTHHTTPSESSIONS=yes

      # Включаем HLS
      - MTX_HLS=yes
      # РАЗРЕШАЕМ CORS (это заменяет ручную пропись заголовков)
      - MTX_HLSALLOWORIGIN=*
      # Всегда передаем заголовки, даже при ошибках
      - MTX_HLSALWAYSTRANSMIT=yes
      # Если все же нужны кастомные заголовки, пишите их ТАК (в кавычках):
#      - MTX_HLSHEADERS_Access-Control-Allow-Methods=GET, POST, OPTIONS, HEAD
      - "MTX_HLSHEADERS=Access-Control-Allow-Methods: GET, POST, OPTIONS, HEAD"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9997/v3/paths/list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pg_tileserv:
    image: pramsey/pg_tileserv:latest
    container_name: pg_tileserv
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER_GEODATA:-postgres}:${POSTGRES_PASSWORD_GEODATA:-password}@${POSTGRES_HOST_GEODATA:-postgres-geodata}:${POSTGRES_PORT_GEODATA:-5432}/${POSTGRES_DB_GEODATA:-geodata_db}
      TS_HTTPPORT: 7800
      TS_CORS_ORIGINS: "*"
      TS_MAX_CONNECTIONS: 20
      TS_SCHEMAS: "geodata"
      TS_BASEURL: "${TILES_BASE_URL:-http://localhost/tiles}"
      TS_TRUST_PROXY: "true"
    depends_on:
      postgres-geodata:
        condition: service_healthy
    restart: always

  # ====== Config, Discovery, Gateway ======
  config-server:
    build:
      context: ./config-server
    container_name: config-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server
    environment:
      EUREKA_INSTANCE_HOSTNAME: discovery-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://127.0.0.1:8080}
      MAX_UPLOAD_SIZE_MB: ${MAX_UPLOAD_SIZE_MB:-1024}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  # ====== Microservices ======
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      AUTH_SERVICE_DOMAIN: ${AUTH_SERVICE_DOMAIN:-http://127.0.0.1:8181}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://127.0.0.1:8181}
      DB_URL: jdbc:postgresql://${POSTGRES_HOST_AUTH}:${POSTGRES_PORT_AUTH}/${POSTGRES_DB_AUTH}
      DB_USER: ${POSTGRES_USER_AUTH}
      DB_PASS: ${POSTGRES_PASSWORD_AUTH}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
#      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
#      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
#      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
#      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
#      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
#      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
#      AZURE_CLIENT_ID: ${YANDEX_CLIENT_ID}
#      AZURE_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
    depends_on:
      postgres-auth:
        condition: service_healthy
      redis-auth:
        condition: service_healthy
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  geodata-service:
    build:
      context: ./geodata-service
    container_name: geodata-service
    environment:
      DB_URL: jdbc:postgresql://${POSTGRES_HOST_GEODATA}:${POSTGRES_PORT_GEODATA}/${POSTGRES_DB_GEODATA}
      DB_USER: ${POSTGRES_USER_GEODATA}
      DB_PASS: ${POSTGRES_PASSWORD_GEODATA}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      postgres-geodata:
        condition: service_healthy
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  document-service:
    build:
      context: ./document-service
    container_name: document-service
    environment:
      DB_URL: jdbc:postgresql://${POSTGRES_HOST_DOCS}:${POSTGRES_PORT_DOCS}/${POSTGRES_DB_DOCS}
      DB_USER: ${POSTGRES_USER_DOCS}
      DB_PASS: ${POSTGRES_PASSWORD_DOCS}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MAX_UPLOAD_SIZE_MB: ${MAX_UPLOAD_SIZE_MB:-1024}
    depends_on:
      postgres-geodata:
        condition: service_healthy
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  geoabstraction-service:
    build:
      context: ./geoabstraction-service
    container_name: geoabstraction-service
    volumes:
      - ./terrain_store:/data/terrain-store
    environment:
      DB_URL: jdbc:postgresql://${POSTGRES_HOST_GEOABSTRACTION}:${POSTGRES_PORT_GEOABSTRACTION}/${POSTGRES_DB_GEOABSTRACTION}
      DB_USER: ${POSTGRES_USER_GEOABSTRACTION}
      DB_PASS: ${POSTGRES_PASSWORD_GEOABSTRACTION}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MAX_UPLOAD_SIZE_MB: ${MAX_UPLOAD_SIZE_MB:-2048}
    depends_on:
      postgres-geoabstraction:
        condition: service_healthy
      titiler:
        condition: service_started
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy


  geoprint-service:
    build:
      context: ./geoprint-service
    container_name: geoprint-service
    environment:
      DB_URL: jdbc:postgresql://${POSTGRES_HOST_GEOPRINT}:${POSTGRES_PORT_GEOPRINT}/${POSTGRES_DB_GEOPRINT}
      DB_USER: ${POSTGRES_USER_GEOPRINT}
      DB_PASS: ${POSTGRES_PASSWORD_GEOPRINT}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MAX_UPLOAD_SIZE_MB: ${MAX_UPLOAD_SIZE_MB:-1024}
      MINIO_EXTERNAL_ENDPOINT: http://${HOST}/minio
    depends_on:
      postgres-geoprint:
        condition: service_healthy
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  geoprint-worker:
    build:
      context: ./geoprint-worker
    container_name: geoprint-worker
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: geo-print
    depends_on:
      kafka:
        condition: service_healthy
      minio:
        condition: service_healthy


  terrain-worker:
    build:
      context: terrain-worker
    container_name: terrain-worker
    volumes:
      - ./terrain_store:/data/terrain-store
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      KAFKA_TOPIC: geoabstraction.terrain.events
    depends_on:
      kafka:
        condition: service_healthy
      minio:
        condition: service_healthy

  geoabstract-worker:
    build:
      context: geoabstract-worker
    container_name: geoabstract-worker
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      KAFKA_TOPIC: geoabstraction.raster.events
    depends_on:
      kafka:
        condition: service_healthy
      minio:
        condition: service_healthy


  geoanalysis-worker:
    build:
      context: geoanalysis-worker
    container_name: geoanalysis-worker
    tmpfs:
      - /app/workspace:size=4G,mode=1777
    deploy:
      resources:
        limits:
          memory: 6G
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      KAFKA_TASKS_TOPIC: geoabstraction.tasks
      KAFKA_RESULTS_TOPIC: geoabstraction.results
    depends_on:
      kafka:
        condition: service_healthy
      minio:
        condition: service_healthy

  search-service:
    build:
      context: ./search-service
    container_name: search-service
    environment:
      ELASTICSEARCH_URI: elasticsearch:9200
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      elasticsearch:
        condition: service_healthy
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy


  stream-service:
    build:
      context: ./stream-service
    container_name: stream-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MEDIAMTX_HLS_DOMAIN: ${MEDIAMTX_HLS_DOMAIN:-http://127.0.0.1:8888}
      MEDIAMTX_SOURCEONDEMAND: ${MEDIAMTX_SOURCEONDEMAND:-false}
      MEDIAMTX_SOURCEONDEMANDCLOSEAFTER: ${MEDIAMTX_SOURCEONDEMANDCLOSEAFTER:-20s}
    depends_on:
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-/}
        VITE_API_GATEWAY_URL: ${VITE_API_GATEWAY_URL:-http://127.0.0.1:8080/api}
        VITE_AUTH_SERVICE_URL: ${VITE_AUTH_SERVICE_URL:-http://127.0.0.1:9001}
        VITE_AUTH_CALLBACK_URL: ${VITE_AUTH_CALLBACK_URL:-http://127.0.0.1:8080/code}
        VITE_ONLYOFFICE_URL: ${VITE_ONLYOFFICE_URL:-http://127.0.0.1:8081}
        VITE_ONLYOFFICE_API_URL: ${VITE_ONLYOFFICE_API_URL:-http://127.0.0.1:9003/api/documents}
    container_name: frontend
    environment:
      __VITE_API_URL__: ${VITE_API_URL:-/}
      __VITE_API_GATEWAY_URL__: ${VITE_API_GATEWAY_URL:-http://127.0.0.1:8080/api}
      __VITE_AUTH_SERVICE_URL__: ${VITE_AUTH_SERVICE_URL:-http://127.0.0.1:9001}
      __VITE_AUTH_CALLBACK_URL__: ${VITE_AUTH_CALLBACK_URL:-http://127.0.0.1:8080/code}
      __VITE_ONLYOFFICE_URL__: ${VITE_ONLYOFFICE_URL:-http://127.0.0.1:8081}
      __VITE_ONLYOFFICE_API_URL__: ${VITE_ONLYOFFICE_API_URL:-http://127.0.0.1:9003/api/documents}

    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s

  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    environment:
      MAX_UPLOAD_SIZE: ${MAX_UPLOAD_SIZE:-1024M}
    volumes:
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/var/log/nginx
      - ./terrain_store:/data/terrain_store
    depends_on:
      - frontend
      - api-gateway
      - auth-service
      - titiler
      - onlyoffice-doc-server
      - mediamtx
      - geoabstraction-service
      - pg_tileserv
    restart: unless-stopped


volumes:
  nginx_cache:
  nginx_logs: