server:
  port: 9005

spring:
  cloud:
    gateway:
      routes:
        - id: geodata-service
          uri: lb://geodata-service
          predicates:
            - Path=/api/geodata/**

        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/api/documents/**
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: j-service-client
          client-secret: j-service-client
          introspection-uri: ${SSO_URL:http://localhost:9001}/oauth2/token-info