server:
  port: 9007

spring:
  application:
    name: geoprint-service
  servlet:
    multipart:
      max-file-size: ${MAX_UPLOAD_SIZE_MB:1024}MB
      max-request-size: ${MAX_UPLOAD_SIZE_MB:1024}MB
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      properties:
        request.timeout.ms: 60000
        session.timeout.ms: 45000
        heartbeat.interval.ms: 3000
        max.poll.interval.ms: 600000
    producer:
      properties:
        request.timeout.ms: 60000
        delivery.timeout.ms: 120000

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-geoprint:5432/print_db}
    username: ${POSTGRES_USER_GEOPRINT:postgres}
    password: ${POSTGRES_PASSWORD_GEOPRINT:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Managed by Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: geoabstraction

  liquibase:
    enabled: true
    change-log: classpath:database/db.changelog.yaml

  auth-types:
    auth-header-enabled: true
    client-credentials-enabled: true
    authorization-code-enabled: true

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${J_SERVICE_CLIENT_ID:j-service-client}
          client-secret: ${J_SERVICE_CLIENT_SECRET:j-service-client}
          introspection-uri: ${SSO_URL:http://auth-service:9001}/oauth2/token-info

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000

minio:
  endpoint: http://minio:9000
  external-endpoint: ${MINIO_EXTERNAL_ENDPOINT:http://localhost/minio}
  access-key: ${MINIO_ROOT_USER:minio_access_key}
  secret-key: ${MINIO_ROOT_PASSWORD:minio_secret_key}
  bucket: geo-print
