server:
  port: 9007

spring:
  application:
    name: terrain-service
  servlet:
    multipart:
      max-file-size: ${MAX_UPLOAD_SIZE_MB:1024}MB
      max-request-size: ${MAX_UPLOAD_SIZE_MB:1024}MB
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-terrain:5432/terrain_db}
    username: ${POSTGRES_USER_TERRAIN:postgres}
    password: ${POSTGRES_PASSWORD_TERRAIN:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Managed by Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: terrain

  liquibase:
    enabled: true
    change-log: classpath:database/db.changelog.yaml

  auth-types:
    auth-header-enabled: true
    client-credentials-enabled: true
    authorization-code-enabled: true

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${J_SERVICE_CLIENT_ID:j-service-client}
          client-secret: ${J_SERVICE_CLIENT_SECRET:j-service-client}
          introspection-uri: ${SSO_URL:http://auth-service:9001}/oauth2/token-info

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000

minio:
  endpoint: http://minio:9000
  access-key: ${MINIO_ROOT_USER:minio_access_key}
  secret-key: ${MINIO_ROOT_PASSWORD:minio_secret_key}
  bucket: terrain
