server:
  port: 9003

spring:
  application:
    name: document-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-docs:5432/docs_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Managed by Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false

  auth-types:
    auth-header-enabled: true
    client-credentials-enabled: true
    authorization-code-enabled: true

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: j-service-client
          client-secret: j-service-client
          introspection-uri: ${SSO_URL:http://auth-service:9001}/oauth2/token-info

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
minio:
  endpoint: http://minio:9000
  access-key: minio_access_key
  secret-key: minio_secret_key
  bucket: documents

onlyoffice:
  jwt-secret: a_very_long_and_secure_secret_key_for_onlyoffice_jwt_32_chars
  callback-base-url: http://minio:9000/api/documents