changeLogFile=database/db.changelog.yaml
driver=org.postgresql.Driver
url=${DB_URL:jdbc:postgresql://postgres-geoabstraction:5432/geoabstraction_db}
username=${POSTGRES_USER_GEOABSTRACTION:postgres}
password=${POSTGRES_PASSWORD_GEOABSTRACTION:password}
defaultSchemaName=geoabstraction
contexts=prod, dev